---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psitransfer-rwo-deployment
  labels:
    app: psitransfer-rwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psitransfer-rwo
  template:
    metadata:
      labels:
        app: psitransfer-rwo
    spec:
      containers:
      - name: psitransfer-rwo-container
        image: psitrax/psitransfer:latest
        ports:
        - containerPort: 3000
        env:
        - name: PSITRANSFER_ADMIN_PASS
          value: "secret"
        volumeMounts:
        - name: psitransfer-rwo-data
          mountPath: /data
        securityContext:
          runAsUser: 0
      volumes:
      - name: psitransfer-rwo-data
        persistentVolumeClaim:
          claimName: psitransfer-rwo-data-claim
---

apiVersion: v1
kind: Service
metadata:
  name: psitransfer-rwo-service
spec:
  selector:
    app: psitransfer-rwo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psitransfer-rwo-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
